### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by davidskeck** [jorio/Nanosaur2#12]
This is so fantastic! I am loving re-living all these classics! Any chance for Air Wings to be remastered? It was 100% my favorite! thank you for doing this!

**Comment by davidskeck** [comment]
Going to close this since it isn't an issue, but please feel free to respond if you can!

**Comment by jorio** [comment]
Glad you're enjoying the games!

I'm not familiar with Air Wings so it's unlikely I'll port that one. I grew up in the Nanosaur/Bugdom era so I'm mostly interested in games from around that time.

Also, Air Wings is still being actively maintained by Pangea - the last update came out last month. You can still play it if you have an iOS device.

**Comment by davidskeck** [comment]
Thanks @jorio! I just played a few rounds of Air Wings! I didn't realize it was still maintained (and that it was battle mode only!) Nanosaur II fills the itch I had for Air Wings anyway.
