### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by rellikmil** [jorio/Nanosaur2#14]
Hi there, there is a Russian version made by "Полёт навигатора", a sub-brand of Akella, the legal localizer and publisher represented in Russia (now defunct)
![Передняя обложка](https://github.com/jorio/Nanosaur2/assets/24569064/8ed1e292-eb6c-49e6-9e00-326d56c0f9f2)
![Диск](https://github.com/jorio/Nanosaur2/assets/24569064/8b8adda0-fc42-4897-993b-580dac14c4c2)

I believe that this localization is legal, but I'm not completely sure about it, you can ask Pangea Software

I think you can somehow adapt this translation here, I'll attach the manual (in HTML, I don't know why they didn't make it in PDF).

These are the kind of files in the game directory, so tell me exactly what you need
![изображение](https://github.com/jorio/Nanosaur2/assets/24569064/3e13efe7-a30d-421a-80b5-af720e73389e)

P.S. probably Akella localized other Pangea Software games too, you should check with them
[Nanosaur Hatchling Russian Manual.zip](https://github.com/user-attachments/files/15890283/Nanosaur.Hatchling.Russian.Manual.zip)

**Comment by jorio** [comment]
Hey, it would be best to re-translate the game from scratch because my version contains more text than the original.
Feel free to submit a PR with your localization as an extra column in [Data/System/strings.csv](https://github.com/jorio/Nanosaur2/blob/master/Data/System/strings.csv).
Once we have localized text, then I can look into adapting the game for Cyrillic fonts.

**Comment by rellikmil** [comment]
And yes, here is Russian dub of story video
[intro.zip](https://github.com/user-attachments/files/15900216/intro.zip)

**Comment by jorio** [comment]
You can download a build with your localization here: https://github.com/jorio/Nanosaur2/actions/runs/9632648716 (Note that the artifact downloads will expire next week)

I'm not going to merge in Akella's dub to steer clear of copyright issues. Fortunately, my version adds subtitles in the intro by default if your language is set to anything else than English, so non-English speakers will still understand the story thanks to your translation.

Feel free to submit a new PR if you want to adjust any text. Thanks!

**Comment by rellikmil** [comment]
@jorio you forgot about manual

**Comment by rellikmil** [comment]
Yes, the game is cool, and everything is clear, the only thing is that when you collected all the eggs, "Enter Wormhole" in English, but it's not essential

**Comment by jorio** [comment]
How would you translate "Enter Wormhole" and "Mission: FAILED"?
I might localize these images when I have time.

**Comment by rellikmil** [comment]
Enter Wormhole = Войдите в червоточину
Mission: FAILED = Задание: ПРОВАЛЕНО
