### ISSUE TITLE
Installing libsdl2-dev on Ubuntu?

### ISSUE THREAD

**Issue by foote-darrell** [jorio/Nanosaur2#8]
[I had followed the build instructions](https://pastebin.com/cNnUT1BC) on this site to modify the game with more render distance and higher height. Reportedly this computer does not have the libsdl2-dev library which was required. I had referred to [this site](https://packages.ubuntu.com/jammy/libsdl2-dev) to download it. I am pretty sure this computer is a x86 architecture, which doesn't seem to be one of the options. I had tried opening one of them, but ti just reports that the dependencies are not met. How do I actually install it?![image](https://user-images.githubusercontent.com/70550621/208570261-7d9f4369-a0e4-4a64-ad7b-e7111d156df0.png)

**Comment by jorio** [comment]
Did you try this? `apt install libsdl2-dev`

**Comment by foote-darrell** [comment]
I tried it. This is what it said:
![image](https://user-images.githubusercontent.com/70550621/209005875-54aa2045-1b85-4b18-923c-6361f3090789.png)

```
darrell@darrell-Lenovo-H430:~$ apt install libsdl2-dev
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
darrell@darrell-Lenovo-H430:~$ 
```

**Comment by malespiaut** [comment]
Hello @foote-darrell,

You must read the error message carefully. It says: “`are you root?`” which implies that you must run the command `apt install libsdl2-dev` as *root*, which is the Linux equivalent for *Administrator* under Windows.

To run any command as root, you can use `sudo`:

`sudo apt install libsdl2-dev`

You will be prompted for your password, and everything will be good to go!
